name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pod install
      run: pod install
    - name: Build
      run: xcodebuild -workspace WeatherMap.xcworkspace -scheme WeatherMap -allowProvisioningUpdates -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
    - name: Build for tests
      run: xcodebuild build-for-testing -workspace WeatherMap.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.3' -scheme WeatherMap -allowProvisioningUpdates -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
    - name: Run tests
      run: xcodebuild test -workspace WeatherMap.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.3' -scheme WeatherMap -allowProvisioningUpdates -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
