name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pod install
      run: pod install
    - name: Build
      run: xcodebuild -workspace WeatherMap.xcworkspace -scheme WeatherMap -allowProvisioningUpdates -sdk iphonesimulator -destination "platform=iOS Simulator, OS=11.4,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
    - name: Run tests
      run: swift test -v
