name: All checks
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Setup:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pod install
      run: pod install
  Build:
    needs: Setup
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -workspace WeatherMap.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.2' -scheme WeatherMap -allowProvisioningUpdates -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
  Tests:
    needs: Setup
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build for tests
      run: xcodebuild build-for-testing -workspace WeatherMap.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.2' -scheme WeatherMap -allowProvisioningUpdates -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
    - name: Run tests
      run: xcodebuild test -workspace WeatherMap.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.2' -scheme WeatherMap -allowProvisioningUpdates -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
