name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Build
      run: bundle exec fastlane buildLane
    - name: Pod install
      run: pod install
    - name: Build
      run: xcodebuild -workspace WeatherMap.xcworkspace  -scheme WeatherMap
    - name: Run tests
      run: swift test -v
